<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>

<!--
*****************************************************************************************
*
*                           =========================
*                              benzene_bringup
*                           =========================
*
*  Launch files and basic startup configuration for the Benzene robot.
*
*****************************************************************************************
-->

<package format="3">

  <!-- Package Information -->
  <name>benzene_bringup</name>
  <version>0.0.0</version>
  <description>Launch files for the Benzene robot and basic files</description>

  <!-- Maintainer Information -->
  <maintainer email="atharvmudse@gmail.com">atharv</maintainer>

  <!-- License -->
  <license>TODO: License declaration</license>

  <!-- Build Dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime Dependencies -->
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>benzene_imu</exec_depend>

  <!-- Testing Dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- Build Type -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>