services:
  benzene:
    container_name: benzene
    image: benzene:latest

    build:
      context: ..
      dockerfile: docker/Dockerfile

    ipc: host
    network_mode: host
    privileged: true

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.Xauthority

    volumes:
      - ${HOME}/atharv/shared/ros2:/root/shared/ros2
      - ${HOME}/.Xauthority:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev

    command:
      - tail
      - -f
      - /dev/null