<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>

<!--
*****************************************************************************************
*
*                         ==============================
*                            benzene_explore_msgs
*                         ==============================
*
*  ROS 2 message definitions for the Benzene exploration package.
*
*****************************************************************************************
-->

<package format="3">

  <!-- Package Information -->
  <name>benzene_explore_msgs</name>
  <version>1.0.0</version>
  <description>ROS 2 message definitions for the Benzene exploration package</description>

  <!-- Author Information -->
  <author email="toluolatubosun@gmail.com">John Olatubosun</author>

  <!-- Maintainer Information -->
  <maintainer email="toluolatubosun@gmail.com">John Olatubosun</maintainer>

  <!-- License -->
  <license>BSD</license>

  <!-- Build Dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Runtime Dependencies -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Interface Package -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <!-- Build Type -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>