<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>

<!--
*****************************************************************************************
*
*                           =========================
*                              benzene_dagger
*                           =========================
*
*  DAgger and teleoperation tools for the Benzene robot.
*
*****************************************************************************************
-->

<package format="3">

  <!-- Package Information -->
  <name>benzene_dagger</name>
  <version>0.0.0</version>
  <description>DAgger and teleoperation tools for the Benzene robot</description>

  <!-- Maintainer Information -->
  <maintainer email="atharvmudse@gmail.com">atharv</maintainer>

  <!-- License -->
  <license>TODO: License declaration</license>

  <!-- Build Dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Package Dependencies -->
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>cv_bridge</depend>

  <!-- Runtime Dependencies -->
  <exec_depend>benzene_gazebo</exec_depend>
  <exec_depend>benzene_bringup</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>python3-opencv</exec_depend>

  <!-- Testing Dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- Build Type -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>